### ISSUE TITLE
Model and Module rando outcomes are not independent  

### ISSUE THREAD

**Issue by LaneDibello** [LaneDibello/Kotor-Randomizer#57]
Model randomization iterates through the already randomized modules when making its changes. As a result you can get different model rando results with the same seed, depending on your Module settings. A fix would be to assure that the model rando occurs before module randomization. Or make use of a look-up table to ensure that the modules are always accessed in the same order.

**Comment by glasnonck** [comment]
Although I'm not yet sure which of the two options would be better for this issue, I think it would be important to understand the appropriate hierarchy of randomization categories - which ones can affect the others, and in what way.

This would help give an idea of where we might need to fix our algorithm and/or change the order of randomization to avoid this issue.

**Comment by glasnonck** [comment]
We won't be able to simply perform model randomization before the modules are shuffled because the module files are copied from the backup directory to the modules directory giving it a new name when it is copied. If models were shuffled beforehand, those changes would be wiped out by the current method of finalizing the module shuffle.

**Comment by glasnonck** [comment]
So there are still two options for how to handle this.

#### 1. Adjust Module Randomization
Module randomization should rename the files in the module directory instead of overwriting them with files from the backup directory. There are some difficulties with this, since the filenames will be changed to ones that already exist in that directory, but it should be fairly straightfoward. Then, model randomization can be safely performed before module randomization.

#### 2. Adjust Model Randomization
Model randomization needs to account for the modules already being shuffled. This means that the RIM files need to be shuffled either in the order of their original filename OR in a consistent order no matter their filename.

Unfortunately, the original filename isn't easily contained within the RIM files. Rims may contain rFiles with the ARE and GIT TypeIDs that contain the "m..." substring as their label. SRims may contain an rFile with TypeID 3003 that contains the "m..." substring at its label.

However, it might be simpler to step through the module lookup based on the original name of each module.
